=== AngelN77/ordinario-ftw/xml/pedidos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="pedidos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pedido" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cliente" type="xs:string"/>
                            <xs:element name="postre" type="xs:string"/>
                            <xs:element name="cantidad" type="xs:integer"/>
                            <xs:element name="estado" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AngelN77/ordinario-ftw/xml/pedidos.xml
<?xml version="1.0" encoding="UTF-8"?>
<pedidos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pedidos.xsd">
    <pedido>
        <cliente>Maria</cliente>
        <postre>Pastel de chocolate</postre>
        <cantidad>2</cantidad>
        <estado>Pendiente</estado>
    </pedido>
    <pedido>
        <cliente>Carlos</cliente>
        <postre>Flan napolitano</postre>
        <cantidad>1</cantidad>
        <estado>Entregado</estado>
    </pedido>
    <pedido>
        <cliente>Ana</cliente>
        <postre>Pay de limón</postre>
        <cantidad>3</cantidad>
        <estado>Pendiente</estado>
    </pedido>
</pedidos>
