=== AngelN77/ordinario-ftw/xml/postres.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="postres">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="postre" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="categoria" type="xs:string"/>
                            <xs:element name="precio" type="xs:decimal"/>
                            <xs:element name="sinAzucar" type="xs:boolean"/>
                            <xs:element name="imagen" type="xs:string"/>
                            <xs:element name="alt" type="xs:string"/>
                            <xs:element name="descripcion" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AngelN77/ordinario-ftw/xml/postres.xml
<?xml version="1.0" encoding="UTF-8"?>
<postres xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="postres.xsd">
    <postre>
        <nombre>Pastel de chocolate</nombre>
        <categoria>Pastel</categoria>
        <precio>80</precio>
        <sinAzucar>false</sinAzucar>
        <imagen>../img/chocolate.svg</imagen>
        <alt>Imagen de pastel de chocolate</alt>
        <descripcion>Pastel sencillo con betún de chocolate.</descripcion>
    </postre>
    <postre>
        <nombre>Flan napolitano</nombre>
        <categoria>Flan</categoria>
        <precio>45</precio>
        <sinAzucar>false</sinAzucar>
        <imagen>../img/flan.svg</imagen>
        <alt>Imagen de flan napolitano</alt>
        <descripcion>Flan casero con caramelo.</descripcion>
    </postre>
    <postre>
        <nombre>Gelatina de fresa</nombre>
        <categoria>Gelatina</categoria>
        <precio>30</precio>
        <sinAzucar>true</sinAzucar>
        <imagen>../img/gelatina.svg</imagen>
        <alt>Imagen de gelatina de fresa</alt>
        <descripcion>Gelatina ligera sabor fresa.</descripcion>
    </postre>
    <postre>
        <nombre>Brownie</nombre>
        <categoria>Galleta</categoria>
        <precio>35</precio>
        <sinAzucar>false</sinAzucar>
        <imagen>../img/brownie.svg</imagen>
        <alt>Imagen de brownie</alt>
        <descripcion>Brownie pequeño con chocolate.</descripcion>
    </postre>
    <postre>
        <nombre>Pay de limón</nombre>
        <categoria>Pastel</categoria>
        <precio>55</precio>
        <sinAzucar>false</sinAzucar>
        <imagen>../img/paylimon.svg</imagen>
        <alt>Imagen de pay de limón</alt>
        <descripcion>Pay frío con sabor a limón.</descripcion>
    </postre>
</postres>
