=== AngelN77/ordinario-ftw/xml/usuarios.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="usuarios">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="usuario" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="password" type="xs:string"/>
                            <xs:element name="rol" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AngelN77/ordinario-ftw/usuarios.xml
<?xml version="1.0" encoding="UTF-8"?>
<usuarios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="usuarios.xsd">
    <usuario>
        <nombre>angel</nombre>
        <password>12345</password>
        <rol>admin</rol>
    </usuario>
    <usuario>
        <nombre>cliente</nombre>
        <password>postres</password>
        <rol>cliente</rol>
    </usuario>
</usuarios>
